# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import framedb_pb2  as framedb__pb2


class ObjectServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SetObject = channel.unary_unary(
                '/framedb.ObjectService/SetObject',
                request_serializer=framedb__pb2.SetObjectRequest.SerializeToString,
                response_deserializer=framedb__pb2.SetObjectResponse.FromString,
                )
        self.GetObject = channel.unary_unary(
                '/framedb.ObjectService/GetObject',
                request_serializer=framedb__pb2.GetObjectRequest.SerializeToString,
                response_deserializer=framedb__pb2.GetObjectResponse.FromString,
                )


class ObjectServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SetObject(self, request, context):
        """Stores the object in FrameDB
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetObject(self, request, context):
        """Retrieves the object from FrameDB
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ObjectServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SetObject': grpc.unary_unary_rpc_method_handler(
                    servicer.SetObject,
                    request_deserializer=framedb__pb2.SetObjectRequest.FromString,
                    response_serializer=framedb__pb2.SetObjectResponse.SerializeToString,
            ),
            'GetObject': grpc.unary_unary_rpc_method_handler(
                    servicer.GetObject,
                    request_deserializer=framedb__pb2.GetObjectRequest.FromString,
                    response_serializer=framedb__pb2.GetObjectResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'framedb.ObjectService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ObjectService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SetObject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/framedb.ObjectService/SetObject',
            framedb__pb2.SetObjectRequest.SerializeToString,
            framedb__pb2.SetObjectResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetObject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/framedb.ObjectService/GetObject',
            framedb__pb2.GetObjectRequest.SerializeToString,
            framedb__pb2.GetObjectResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
