# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: framedb.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rframedb.proto\x12\x07\x66ramedb\"I\n\x06Object\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x12\n\nframedb_id\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\x12\x10\n\x08metadata\x18\x04 \x01(\t\"3\n\x10SetObjectRequest\x12\x1f\n\x06object\x18\x01 \x01(\x0b\x32\x0f.framedb.Object\"5\n\x11SetObjectResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x1f\n\x10GetObjectRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"T\n\x11GetObjectResponse\x12\r\n\x05\x66ound\x18\x01 \x01(\x08\x12\x1f\n\x06object\x18\x02 \x01(\x0b\x32\x0f.framedb.Object\x12\x0f\n\x07message\x18\x03 \x01(\t2\x97\x01\n\rObjectService\x12\x42\n\tSetObject\x12\x19.framedb.SetObjectRequest\x1a\x1a.framedb.SetObjectResponse\x12\x42\n\tGetObject\x12\x19.framedb.GetObjectRequest\x1a\x1a.framedb.GetObjectResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'framedb_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_OBJECT']._serialized_start=26
  _globals['_OBJECT']._serialized_end=99
  _globals['_SETOBJECTREQUEST']._serialized_start=101
  _globals['_SETOBJECTREQUEST']._serialized_end=152
  _globals['_SETOBJECTRESPONSE']._serialized_start=154
  _globals['_SETOBJECTRESPONSE']._serialized_end=207
  _globals['_GETOBJECTREQUEST']._serialized_start=209
  _globals['_GETOBJECTREQUEST']._serialized_end=240
  _globals['_GETOBJECTRESPONSE']._serialized_start=242
  _globals['_GETOBJECTRESPONSE']._serialized_end=326
  _globals['_OBJECTSERVICE']._serialized_start=329
  _globals['_OBJECTSERVICE']._serialized_end=480
# @@protoc_insertion_point(module_scope)
