apiVersion: apps/v1
kind: Deployment
metadata:
  name: routing-service
  namespace: framedb-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: routing-service
  template:
    metadata:
      labels:
        app: routing-service
    spec:
      containers:
        - name: routing-service
          image: framedb/routing-service:v1
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_URL
              value: "mongodb://framedb-0.framedb-db.svc.cluster.local:27017"
---
apiVersion: v1
kind: Service
metadata:
  name: routing-service-svc
  namespace: framedb-services
spec:
  selector:
    app: routing-service
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30611
  type: NodePort
