apiVersion: v1
kind: Service
metadata:
  name: <pod-name>-svc
  namespace: framedb-storage
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind: Mapping
      name: <pod-name>-svc
      prefix: /<pod-name>/
      rewrite : /
      service: <pod-name>-svc.framedb-storage.svc.cluster.local:5000
spec:
  selector:
    app: <pod-name>
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP