FROM streamer_cpu:latest

#this builds a CPU image 

RUN apt update -y && apt install -y ffmpeg
RUN pip3 install requests

COPY . /gst-build/video_ingestion
COPY setup_env.sh /gst-build/
COPY env_cpu.sh /gst-build
COPY build.sh /
COPY gst-python-build.1.19.0.1.build gst-build/gst-python/meson.build

RUN chmod 777 /build.sh

WORKDIR /gst-build

#build gstreamer-cpu mode
RUN meson configure build/ && ninja -C build/;

#install ingestion_library used for TiDB 
RUN pip3 install -e video_ingestion/ingestion_library

#install routing_libary used for in-memory routing system
RUN pip3 install -e video_ingestion/routing_library

RUN chmod 777 env.sh
RUN chmod 777 setup_env.sh


ENTRYPOINT ["./env.sh" ]